# Generated by Django 4.1.5 on 2023-01-19 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DealsOfTheDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_name', models.CharField(default='', max_length=50)),
                ('prod_desc', models.CharField(default='', max_length=100)),
                ('prod_price', models.IntegerField()),
                ('image', models.ImageField(default='', upload_to='app/images')),
            ],
        ),
    ]
